# ==========================
# Application
# ==========================
spring.application.name=AetherGate

# ==========================
# Server
# ==========================
server.port=8080

# ==========================
# PostgreSQL Database
# ==========================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Logging
# ==========================
logging.level.org.springframework=INFO
logging.level.com.aethergate.gateway=DEBUG

# ==========================
# JWT Configuration
# ==========================
spring.profiles.active=gemini,groq

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

gemini.base.url=https://generativelanguage.googleapis.com
gemini.api.key= gemini.api.key=${GEMINI_API_KEY}

openai.base.url=https://api.openai.com/v1
openai.api.key=${OPENAI_API_KEY}

groq.base.url=https://api.groq.com/openai/v1
groq.api.key=${GROQ_API_KEY}